
: ${CONCERT_WORKFLOW_ENGINE_BLOCKLY_SERVER_PORT:=9999}
: ${CONCERT_WORKFLOW_ENGINE_BLOCKLY_ROSBRIDGE_URL:=ws://localhost:9090}
: ${CONCERT_WORKFLOW_ENGINE_BLOCKLY_COMPOSER_URL:=http://composer.robotconcert.org:9999}
: ${CONCERT_WORKFLOW_ENGINE_BLOCKLY_DELAY_AFTER_TOPICS:=2000}
: ${CONCERT_WORKFLOW_ENGINE_BLOCKLY_PUBLISH_DELAY:=100}
: ${CONCERT_WORKFLOW_ENGINE_BLOCKLY_LOG_LEVEL:=info}
  
#Exports
export CONCERT_WORKFLOW_ENGINE_BLOCKLY_SERVER_PORT
export CONCERT_WORKFLOW_ENGINE_BLOCKLY_ROSBRIDGE_URL
export CONCERT_WORKFLOW_ENGINE_BLOCKLY_COMPOSER_URL
export CONCERT_WORKFLOW_ENGINE_BLOCKLY_DELAY_AFTER_TOPICS
export CONCERT_WORKFLOW_ENGINE_BLOCKLY_PUBLISH_DELAY
export CONCERT_WORKFLOW_ENGINE_BLOCKLY_LOG_LEVEL